### ISSUE TITLE
Words in code boxes and date seem to flicker when cursor moves

### ISSUE THREAD

**Issue by adventl** [eye-sigil/Discord-Prism#4]
I'm not too sure how to describe it or if its intend or not, but the words in code boxes and the date and time of chats seem to flicker a little when you move your mouse over the chat area.

I think it might have something to do with one of the transparencies.

Does not happen when moving the mouse around the channel members area on the right as well as the channel selector on the left.

:)

**Comment by polyjitter** [comment]
Do you mean it seems to lose and gain thickness? If so, that happens in the default theme too and I can't do much to fix it.

**Comment by adventl** [comment]
The date seems to become a little blurry and loses focus.

The name colors seem to become a bit more pale.

I've tried restarting Discord with an empty CSS file but it doesn't seem to happen with the empty CSS file though.

I'll try to make a video of what I'm talking about.

Got the video, how do I send the YT URL to you? :)

**Comment by polyjitter** [comment]
Please do. I have never encountered this.

**Comment by adventl** [comment]
https://www.youtube.com/watch?v=GZVsOtZ0mN4

Here is the link.

**Comment by polyjitter** [comment]
Unfortunately, this is default behavior in Discord itself, it's just less
noticeable in the default theme. Not sure there's anything I can do about
it.

**Comment by adventl** [comment]
Ahh ohk, sorry about opening the issue then!
